version: '3'

services:

  resumefx:
    build: ./
    image: resumefx:1.0.0
    container_name: resumefx
    restart: always
    stdin_open: true
    tty: true
    ports:
      - 18080:8080
    command: ./bin/restart.sh
    volumes:
      - data:/resume-fx-jpro/data/
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail", "http://localhost:8080/status/alive"]
      interval: 1m30s
      timeout: 10s
      retries: 3


volumes:
  data:
    driver: local
    driver_opts:
      device: /var/www/cv3d.tangorabox.com/web/CV3D_Data
      o: bind
      type: none
